load("@rules_m4//m4/internal:toolchain_alias.bzl", "m4_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

m4_toolchain_alias(
    name = "current_m4_toolchain",
    visibility = ["//visibility:public"],
)
