load("//m4:toolchain.bzl", "m4_toolchain")

m4_toolchain(
    name = "toolchain",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "toolchain_type",
    visibility = ["@io_bazel_rules_m4//m4/toolchains:__pkg__"],
)
