load("//m4:m4.bzl", "m4_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

m4_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
