cc_binary(
    name = "capture_stdout",
    srcs = ["capture_stdout.c"],
    visibility = ["@io_bazel_rules_m4//m4/toolchains:__pkg__"],
)

cc_binary(
    name = "deny_shell",
    srcs = ["deny_shell.c"],
    visibility = ["@io_bazel_rules_m4//m4/toolchains:__pkg__"],
)
