filegroup(
    name = "m4_repository_ext_bzl",
    srcs = ["m4_repository_ext.bzl"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "m4_toolchains_ext_bzl",
    srcs = ["m4_toolchains_ext.bzl"],
    visibility = ["//:__subpackages__"],
)
